on:
  workflow_dispatch:
  push:

jobs:
  check:
    name: Check modified image files
    outputs:
      should-run: ${{ steps.check.outputs.should-run }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: check modified files
        id: check
        run: |
          if make check; then
            echo "image files were modified"
            echo "should-run=true" >> $GITHUB_OUTPUT
          else
            echo "image files were NOT modified"
            echo "should-run=false" >> $GITHUB_OUTPUT
          fi

  call:
    uses: ./.github/workflows/exiftool.yml
    name: Call exiftool
    needs: check
    if:  ${{ needs.check.outputs.should-run == 'true' }}
